version: '3.2'
services:
  tickets-service:
    build:
      dockerfile: Dockerfile
    
    volumes:
      - D:/tickets/files/:/tmp/tickets/files/
    ports:
      - 48659:48659
networks:
  default:
    external:
      name: zcts_default   